/* Oppgave 1 */

/* schema.sql */

CREATE TABLE Lager
(
    LID INTEGER AUTO_INCREMENT NOT NULL,
    Navn VARCHAR(50) NOT NULL,
    Adresse VARCHAR(50) NOT NULL,
    PRIMARY KEY (LID)
);

CREATE TABLE Pakke
(
    PID INTEGER AUTO_INCREMENT NOT NULL,
    LID INTEGER NOT NULL,
    Eier VARCHAR(50) NOT NULL,
    Vekt DOUBLE PRECISION NOT NULL,
    Volum DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (PID),
    FOREIGN KEY (LID) REFERENCES Lager(LID)
);

CREATE TABLE Bruker
(
    BID INTEGER AUTO_INCREMENT NOT NULL,
    Navn VARCHAR(50) NOT NULL,
    Passord VARCHAR(50) NOT NULL,
    PRIMARY KEY (BID)
);

